---
- name: Deploy haha.sh and configure cron
  hosts: all
  become: true

  tasks:
    - name: Place haha.sh in /opt
      copy:
        dest: /opt/haha.sh
        mode: '0755'
        content: |
          #!/bin/bash

          sleep 60

          IP=$(ip a show eth0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)
          IP_SED=$IP"99"

          sed -i "s#$IP#$IP_SED#g" /etc/network/interfaces.d/50-cloud-init.cfg

          systemctl restart networking.service

    - name: Add cron job to run haha.sh at reboot
      cron:
        name: "run haha.sh on reboot"
        special_time: reboot
        job: "/bin/bash /opt/haha.sh"
